name: Continuous Integration
on:
  push:
jobs:
  norm:
    name: norminette
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Run Norminette
        run: make norm
  unit_test:
    name: unit_test
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build pipex
        run: make
      - name: Unit test
        run: make test
  rspec:
    name: rspec test
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build pipex
        run: make
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: rspec test/spec
